name: test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install paho-mqtt requests coverage coveralls
    - name: Print versions
      run: |
        python -c 'import paho.mqtt; print("Paho MQTT " + paho.mqtt.__version__)'
        python -c 'import requests; print("Requests " + requests.__version__)'
    - name: Run tests
      run: python -m coverage run -m unittest discover
    - name: Print coverage report
      run: python -m coverage report
    - name: Upload coverage
      run: coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
